runtime: nodejs20

env_variables:
  NODE_ENV: "production"
  PORT: "8080"  # Google App Engine akan otomatis set PORT ke 8080
  FIREBASE_API_KEY: "AIzaSyAFPdpL4cY9WqMrJpHX6L3cATjOhl1r-W8"
  FIREBASE_AUTH_DOMAIN: "undangan-nikah-77b33.firebaseapp.com"
  FIREBASE_PROJECT_ID: "undangan-nikah-77b33"
  FIREBASE_STORAGE_BUCKET: "undangan-nikah-77b33.appspot.com"
  FIREBASE_MESSAGING_SENDER_ID: "505134324758"
  FIREBASE_APP_ID: "1:505134324758:web:fec2fd3b8edccb255ea937"
  FIREBASE_MEASUREMENT_ID: "G-89TBJH49BW"
  FIREBASE_DATABASE_URL: "https://undangan-nikah-77b33.firebaseio.com"

  # JWT Configuration
  JWT_SECRET: "your_super_secret_jwt_key_change_this_in_production"
  JWT_EXPIRES_IN: "1h"
  JWT_REFRESH_EXPIRES_IN: "7d"

  # Cookie Configuration
  COOKIE_SECRET: "your_cookie_secret_key_change_this_in_production"

  # CORS Configuration
  ALLOWED_ORIGINS: "*"
